sudo: required

services:
- docker

arch:
    packages:
    - base-devel
    - lib32-gcc-libs
    script:
    - make

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"

notifications:
    email:
        on_success: change
        on_failure: change
